import java.io.Serializable;

public class PrivKey implements Serializable{

	private static final long serialVersionUID = 4685779861648221454L;                      //Autogenerated serial for serializable
	public LargeInteger d, n;
    public PrivKey(LargeInteger d, LargeInteger n){
        this.d = d;
        this.n = n;
    }

}