import java.io.Serializable;

public class PubKey implements Serializable
{
    private static final long serialVersionUID = 303258608784561803L;                                           //Autogenerated serial number for serializable
    public LargeInteger e, n;
    public PubKey(LargeInteger e, LargeInteger n){
        this.e = e;
        this.n = n;
    }   
}